name: Bundle Zanolife

on:
  push:
    branches: [ master ]

jobs:
  buildWebpack:
    runs-on: ubuntu-latest
    steps:
      - name: Build webpack
        uses: actions/checkout@v2
        with:
          ref: www
          script: |
            npm run build
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Webpack generated"
            git push
