name: Bundle Zanolife

on:
  push:
    branches: [ master ]
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-16.04
    steps:
      - name: build and deploy
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: |
          npm i
          npm run build
          rm -r docs
          mv dist/* /docs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m "Webpack generated"
          git push
